@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Foodnotes *-down-> "1" UniqueStallList
UniqueStallList *-right-> "*" Stall
Stall *-down-> "1" Name
Stall *-down-> "1" StallReview
Stall *-right-> "0...1" Menu
Menu *-right-> "1" UniqueItemList
UniqueItemList *-down-> "*" Item
Item *-down-> "1" ItemReview
ItemReview *-down-> "1" ItemRating
ItemReview *-down-> "1" ItemDescription

@enduml
