@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":DeleteStallCommandParser" as DeleteStallCommandParser LOGIC_COLOR
participant "d:DeleteStallCommand" as DeleteStallCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete-stall s/1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("delete stall s/1")
activate AddressBookParser

create DeleteStallCommandParser
AddressBookParser -> DeleteStallCommandParser
activate DeleteStallCommandParser

DeleteStallCommandParser --> AddressBookParser
deactivate DeleteStallCommandParser

AddressBookParser -> DeleteStallCommandParser : parse("s/1")
activate DeleteStallCommandParser

create DeleteStallCommand
DeleteStallCommandParser -> DeleteStallCommand
activate DeleteStallCommand

DeleteStallCommand --> DeleteStallCommandParser : d
deactivate DeleteStallCommand

DeleteStallCommandParser --> AddressBookParser : d
deactivate DeleteStallCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteStallCommandParser -[hidden]-> AddressBookParser
destroy DeleteStallCommandParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> DeleteStallCommand : execute()
activate DeleteStallCommand

DeleteStallCommand -> Model : deleteStall(1)
activate Model

Model --> DeleteStallCommand
deactivate Model

create CommandResult
DeleteStallCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteStallCommand
deactivate CommandResult

DeleteStallCommand --> LogicManager : result
deactivate DeleteStallCommand

[<--LogicManager
deactivate LogicManager
@enduml
